### ISSUE TITLE
Inkscape cannot be installed via autopkg

### ISSUE THREAD

**Issue by hugo4711** [autopkg/homebysix-recipes#200] opened 2019-02-06 14:31 UTC
mac-server:~ admin$ autopkg run -vv Inkscape.munki
Processing Inkscape.munki...
WARNING: Inkscape.munki is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': u'(Current stable version: (?P<version>[0-9]{1,2}.[0-9]{1,2}.[0-9]{1,2}))',
           'url': u'https://inkscape.org/en/'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (version): 0.92.4
URLTextSearcher: Found matching text (match): Current stable version: 0.92.4
{'Output': {'match': 'Current stable version: 0.92.4', u'version': '0.92.4'}}
URLTextSearcher
{'Input': {'CURL_PATH': '/usr/bin/curl',
           're_pattern': u'(?P<url>\\/en\\/release.*dmg\\/dl\\/)',
           'result_output_var_name': 'match',
           'url': u'https://inkscape.org/en/release/0.92.4/mac-os-x/'}}
No match found on URL: https://inkscape.org/en/release/0.92.4/mac-os-x/
Failed.
Receipt written to /Users/admin/Library/AutoPkg/Cache/com.github.homebysix.munki.Inkscape/receipts/Inkscape-receipt-20190206-152919.plist

The following recipes failed:
    Inkscape.munki
        Error in com.github.homebysix.munki.Inkscape: Processor: URLTextSearcher: Error: No match found on URL: https://inkscape.org/en/release/0.92.4/mac-os-x/

Nothing downloaded, packaged or imported.

**Comment by homebysix** [comment] 2019-02-06 16:51
Duplicate of https://github.com/autopkg/homebysix-recipes/issues/197.

**Closed by homebysix** 2019-02-06 16:51 UTC
