### ISSUE TITLE
Zoom.pkg.recipe error

### ISSUE THREAD

**Issue by kitzy** [autopkg/homebysix-recipes#186] opened 2018-10-25 17:18 UTC
Error in com.github.homebysix.pkg.Zoom: Processor: Unarchiver: Error: Unarchiving /Users/kitzy/Library/AutoPkg/Cache/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip with ditto failed: ditto: /Users/kitzy/Library/AutoPkg/Cache/com.github.homebysix.pkg.Zoom/expanded/Scripts/7zr.zip: No such file or directory

**Comment by homebysix** [comment] 2018-10-25 17:19
This might be a duplicate of https://github.com/autopkg/homebysix-recipes/issues/173?

**Comment by homebysix** [comment] 2018-12-05 18:08
I've merged #177, which should solve this issue.

**Closed by homebysix** 2018-12-05 18:08 UTC
