### ISSUE TITLE
Parallels Desktop 18 Failing On CodeSignatureVerifier

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/homebysix-recipes#596] opened 2023-06-30 14:51 UTC
Hi, @homebysix 

Parallels Desktop when set to download version 18 is failing to download the App dmg. 

```
autopkg run -vv /Users/paul/Documents/GitHub/AutoPkg\ Repos/homebysix-recipes/Parallels/ParallelsDesktop.munki.recipe 
Processing /Users/paul/Documents/GitHub/AutoPkg Repos/homebysix-recipes/Parallels/ParallelsDesktop.munki.recipe...
WARNING: /Users/paul/Documents/GitHub/AutoPkg Repos/homebysix-recipes/Parallels/ParallelsDesktop.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': '(https.*?18(.*?)(?=\\?|\\"))',
           'result_output_var_name': 'url_version',
           'url': 'https://download.parallels.com/website_links/desktop/18/builds-en_US.json'}}
URLTextSearcher: Found matching text (url_version): https://link.parallels.com/link/647db18dvv94/
{'Output': {'url_version': 'https://link.parallels.com/link/647db18dvv94/'}}
URLDownloader
{'Input': {'filename': 'Parallels Desktop.dmg',
           'url': 'https://link.parallels.com/link/647db18dvv94/'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Thu, 08 Jun 2023 12:07:37 GMT
URLDownloader: Storing new ETag header: "6481c489-2c6d1ba"
URLDownloader: Downloaded /Users/paul/Library/AutoPkg/Cache/com.github.homebysix.munki.ParallelsDesktop/downloads/Parallels Desktop.dmg
{'Output': {'download_changed': True,
            'etag': '"6481c489-2c6d1ba"',
            'last_modified': 'Thu, 08 Jun 2023 12:07:37 GMT',
            'pathname': '/Users/paul/Library/AutoPkg/Cache/com.github.homebysix.munki.ParallelsDesktop/downloads/Parallels '
                        'Desktop.dmg',
            'url_downloader_summary_result': {'data': {'download_path': '/Users/paul/Library/AutoPkg/Cache/com.github.homebysix.munki.ParallelsDesktop/downloads/Parallels '
                                                                        'Desktop.dmg'},
                                              'summary_text': 'The following '
                                                              'new items were '
                                                              'downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'input_path': '/Users/paul/Library/AutoPkg/Cache/com.github.homebysix.munki.ParallelsDesktop/downloads/Parallels '
                         'Desktop.dmg/Parallels Desktop.app',
           'requirement': 'anchor apple generic and (certificate '
                          'leaf[field.1.2.840.113635.100.6.1.9] /* exists */ '
                          'or certificate 1[field.1.2.840.113635.100.6.2.6] /* '
                          'exists */ and certificate '
                          'leaf[field.1.2.840.113635.100.6.1.13] /* exists */ '
                          'and certificate leaf[subject.OU] = "4C6364ACXT")'}}
CodeSignatureVerifier: Mounted disk image /Users/paul/Library/AutoPkg/Cache/com.github.homebysix.munki.ParallelsDesktop/downloads/Parallels Desktop.dmg
Error processing path '/private/tmp/dmg.S0WmiI/Parallels Desktop.app' with glob. 
Failed.
Receipt written to /Users/paul/Library/AutoPkg/Cache/com.github.homebysix.munki.ParallelsDesktop/receipts/ParallelsDesktop.munki-receipt-20230630-153946.plist

The following recipes failed:
    /Users/paul/Documents/GitHub/AutoPkg Repos/homebysix-recipes/Parallels/ParallelsDesktop.munki.recipe
        Error in com.github.homebysix.munki.ParallelsDesktop: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.S0WmiI/Parallels Desktop.app' with glob. 

The following new items were downloaded:
    Download Path                                                                                                  
    -------------                                                                                                  
    /Users/paul/Library/AutoPkg/Cache/com.github.homebysix.munki.ParallelsDesktop/downloads/Parallels Desktop.dmg 
```

The regex is picking up the SDK package and downloading that. 

```
{
      "file": "https://link.parallels.com/link/647db18dvv94/",
      "name": "Parallels Virtualization SDK 18 for Mac",
      "description": "MD5 checksum: ef5983b936af26c5c191254a80447fd7"
    }
```

I'll hopefully have some time to look at a PR next week if you (or anyone else!) are unable to get round to it

**Comment by paul-cossey** [comment] 2023-06-30 14:53
FWIW Versions 16 and 17 seem uneffected.

**Comment by mpanighetti** [comment] 2023-07-03 17:52
Looks like it's an issue with the regex patterns on https://download.parallels.com/website_links/desktop/18/builds-en_US.json. Parallels Desktop 18's link no longer includes "18" in its download string (currently https://link.parallels.com/link/647d9b87kOse/?experience=enter_key), and the additional "Parallels Virtualization SDK 18 for Mac" coincidentally has a `18` in its link (currently https://link.parallels.com/link/647db18dvv94/).

The expected link of https://www.parallels.com/directdownload/pd18/image/?experience=enter_key does still work and is downloading the correct file, but the regex logic will need to be adjusted since this JSON no longer includes a link in that format.

**Comment by mpanighetti** [comment] 2023-07-03 21:27
#597 resolves this issue; confirmed in my testing that my new regex pattern grabs the correct URL in Parallels Desktop major versions 10-18 (test output included in PR). My new regex checks the JSON object name rather than the URL itself, then grabs the download URL corresponding to the correct name.

**Comment by homebysix** [comment] 2023-07-03 21:42
Merged https://github.com/autopkg/homebysix-recipes/pull/597.

**Closed by homebysix** 2023-07-03 21:42 UTC
