### ISSUE TITLE
ForkLift Download has mode 700

### ISSUE THREAD

**Issue by soberhofer** [autopkg/homebysix-recipes#157] opened 2018-03-21 10:47 UTC
Hello,

technically this is not an issue with the Recipe, but in the current Version of Forklift (3.2) the .app that is contained in the .zip referenced in the sparkle feed has mode 700, so if the mode is not changed, the user will not be able to execute. If Forklift continues to do this it might make sense to amend the recipe to change the mode to 755 (in this case i just edited the pkgsinfo for munki).

**Comment by gregneagle** [comment] 2018-03-21 15:50
Have you also reported the issue to the Forklift developer?

**Comment by soberhofer** [comment] 2018-03-22 11:15
Forklift has updated it's sparkle feed (and they released 3.2.1) and now it's completely broken. (it returns './/' as Download URL, so i guess we'll have to wait for 3.2.2.

"We discovered an issue in ForkLift 3.2 that prevents the auto-update process to install the newer version. Please download this update manually from here and move it to your Applications folder using Finder. Sorry for the inconvenience. "

**Comment by franton** [comment] 2018-03-30 20:37
This seems to be a common issue with apps using the Sparkle framework lately. My CocoaPods issue is an effective duplicate of this.

**Comment by homebysix** [comment] 2019-09-06 15:53
This appears to be fixed as of Fork 3.3.4.

**Closed by homebysix** 2019-09-06 15:53 UTC
