### ISSUE TITLE
Google Hangouts Chat

### ISSUE THREAD

**Issue by mikecalbreeeezy** [autopkg/homebysix-recipes#204] opened 2019-03-02 00:44 UTC
Hello,

I tried to deploy the Google Hangouts Chat pkg file through JAMF. It completes but then i get the error that 'Chat cannot be opened because of a problem. Check with the developer to make sure Chat works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.' I am on Mojave 10.14.3.

**Comment by homebysix** [comment] 2019-03-02 00:49
Hi! Sounds like a dupe of https://github.com/autopkg/homebysix-recipes/issues/203, resolved earlier today. Try updating your repo recently?

**Closed** 2019-03-03 05:38 UTC

**Comment by mikecalbreeeezy** [comment] 2019-03-04 23:26
Thanks for the help! I'm really new to autopkg and Jamf. Do you have a
tutorial to help on how to package applications to be able to deploy to JSS?

**Comment by homebysix** [comment] 2019-03-05 16:46
Hi @mikecalbreeeezy — If you're new to Jamf, I'd recommend configuring your JSS manually with the policies, smart groups, and extension attributes you need for a while. Familiarity with those core pieces is essential before automation will be useful to you. After that, I'd recommend using AutoPkg "pkg" recipes to ease the packaging process, and manually upload the results to Jamf when needed. Finally if you want to automate further, the new JSSImporter repo [read me](https://github.com/jssimporter/JSSImporter) and [wiki](https://github.com/jssimporter/JSSImporter/wiki) has quite a bit of additional information. Hope that helps!

**Comment by mikecalbreeeezy** [comment] 2019-03-05 18:21
I downloaded an updated copy of the recipe and looks like there are still some users that are experiencing the issue with the wrong version of chat being installed.

**Comment by homebysix** [comment] 2019-03-06 17:29
Hi @mikecalbreeeezy - Did you clear your AutoPkg cache before running the recipe again? Even with the fix, PkgCreator will not build a new package if a previous one with the same name and version exists.
